DATA_LOCATION = 'data/data_1.json'
VALIDATION_DATA_LOCATION = 'data/ticket8-9.json'
CLASSIFIER_EXPORT_LOCATION = 'models/model.pkl'
MODEL_EXPORT_LOCATION = 'models/model.h5'
CHECKPOINTER_MODEL_EXPORT_LOCATION = 'models/checkpointer_model.h5'
DL_TFIDF_EXPORT_LOCATION = 'models/dl_tfidf.pkl'
ML_TFIDF_EXPORT_LOCATION = 'models/ml_tfidf.pkl'
TOKENIZER_EXPORT_LOCATION = 'models/tokenizer.pkl'
LABLE_ENCODER_EXPORT_LOCATION = 'models/label_ancoder.pkl'

MIN_SAMPLE_PER_CLASS = 2
TRAIN_SET_SIZE = 0.8
VOCABULARY_SIZE = 10000
MAXLEN = 100
EPOCHS = 10
BATCH_SIZE = 128
EMBEDDING_DIM = 64
DROPOUT = 0.5